apps/gameadmin/urls.py
from django.conf.urls import url
from django.conf.urls import url
from . import views
urlpatterns = [

    # Delete URLS
    url(r'^delete_monster$', views.delete_monster, name='delete_monster'),
    url(r'^delete_item$', views.delete_item, name='delete_item'),
    url(r'^delete_room$', views.delete_room, name='delete_room'),
    url(r'^delete_trap$', views.delete_trap, name='delete_trap'),
    url(r'^delete_treasure$', views.delete_treasure, name='delete_treasure'),
    url(r'^delete_user$', views.delete_user, name='delete_user'),
    url(r'^delete_character$', views.delete_character, name='delete_character'),
    #Assign URLS
    url(r'^assign_monster$', views.assign_monster, name='assign_monster'),
    url(r'^assign_trap$', views.assign_trap, name='assign_trap'),
    url(r'^assign_treasure$', views.assign_treasure, name='assign_treasure'),
    url(r'^assign_visitor$', views.assign_visitor, name='assign_visitor'),
    url(r'^assign_explorer$', views.assign_explorer, name='assign_explorer'),
    url(r'^assign_killer$', views.assign_killer, name='assign_killer'),
    url(r'^assign_item$', views.assign_item, name='assign_item'),
    #Select links URLS
    url(r'^room_monster$', views.room_monster, name='room_monster'),
    url(r'^room_visitor$', views.room_visitor, name='room_visitor'),
    url(r'^room_explorer$', views.room_explorer, name='room_explorer'),
    url(r'^room_trap$', views.room_trap, name='room_trap'),
    url(r'^room_treasure$', views.room_treasure, name='room_treasure'),
    url(r'^room_killer$', views.room_killer, name='room_killer'),
    url(r'^room_exit$', views.room_exit, name='room_exit'),
    url(r'^character_item', views.character_item, name='character_item'),
    #Add URLS
    url(r'^add_monster$', views.add_monster, name='add_monster'),
    url(r'^add_item$', views.add_item, name='add_item'),
    url(r'^add_room$', views.add_room, name='add_room'),
    url(r'^add_trap$', views.add_trap, name='add_trap'),
    url(r'^add_treasure$', views.add_treasure, name='add_treasure'),
    url(r'^add_exit$', views.add_exit, name='add_exit'),
    #Remove URLS
    url(r'^remove_killer$', views.remove_killer, name='remove_killer'),
    url(r'^remove_treasure$', views.remove_treasure, name='remove_treasure'),
    url(r'^remove_monster$', views.remove_monster, name='remove_monster'),
    url(r'^remove_visitor$', views.remove_visitor, name='remove_visitor'),
    url(r'^remove_explorer$', views.remove_explorer, name='remove_explorer'),
    url(r'^remove_trap$', views.remove_trap, name='remove_trap'),
    url(r'^remove_character$', views.remove_character, name='remove_character'),
    #Admin URLS
    url(r'^admin_characters$', views.admin_characters, name='admin_characters'),
    url(r'^admin_items$', views.admin_items, name='admin_items'),
    url(r'^admin_monsters$', views.admin_monsters, name='admin_monsters'),
    url(r'^admin_rooms$', views.admin_rooms, name='admin_rooms'),
    url(r'^admin_traps$', views.admin_traps, name='admin_traps'),
    url(r'^admin_treasure$', views.admin_treasure, name='admin_treasure'),
    url(r'^admin_users$', views.admin_users, name='admin_users'),
    #Edit URLS
    url(r'^edit_user/(?P<id>\d+)$', views.edit_user, name='edit_user'),
    url(r'^edit_character/(?P<id>\d+)$', views.edit_character, name='edit_character'),
    url(r'^edit_monster/(?P<id>\d+)$', views.edit_monster, name='edit_monster'),
    url(r'^edit_item/(?P<id>\d+)$', views.edit_item, name='edit_item'),
    url(r'^edit_treasure/(?P<id>\d+)$', views.edit_treasure, name='edit_treasure'),
    url(r'^edit_trap/(?P<id>\d+)$', views.edit_trap, name='edit_trap'),
    url(r'^edit_room/(?P<id>\d+)$', views.edit_room, name='edit_room'),
    #Update URLS
    url(r'^update_user$', views.update_user, name='update_user'),
    url(r'^update_character$', views.update_character, name='update_character'),
    url(r'^update_monster$', views.update_monster, name='update_monster'),
    url(r'^update_item$', views.update_item, name='update_item'),
    url(r'^update_treasure$', views.update_treasure, name='update_treasure'),
    url(r'^update_trap$', views.update_trap, name='update_trap'),
    url(r'^update_room$', views.update_room, name='update_room'),
    #Catch All (DONT MOVE)
    url(r'^$', views.index,  name='index'),
]

thegame/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^game/', include('apps.game.urls', namespace='Game')),
    url(r'^mainmenu/', include('apps.mainmenu.urls', namespace='Mainmenu')),
    url(r'^login/', include('apps.login.urls', namespace='Login')),
    url(r'^admin/', include('apps.gameadmin.urls', namespace='Admin')),
    url(r'^', include('apps.login.urls', namespace='Login')),
]

apps/gameadmin/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.

apps/gameadmin/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.template import Context
from random import randint
from ..game.models import Users, Characters, Monsters, Rooms, Items, Traps, Treasures, Exits



def index(request):
    context = {
        'users': Users.objects.all().order_by('username'),
        'characters': Characters.objects.all().order_by('name'),
        'monsters': Monsters.objects.all().order_by('name'),
        'rooms': Rooms.objects.all().order_by('id'),
        'items': Items.objects.all().order_by('name'),
        'traps': Traps.objects.all().order_by('name'),
        'treasures': Treasures.objects.all().order_by('name'),
        'exits': Exits.objects.all(),
        }
    return render(request, 'gameadmin/megaadd.html', context)



# first half of assigning objects display all options for X_Y
# TODO add filters for all room_ rooms
def room_exit(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'exits': Exits.objects.all(),
        'rooms': Rooms.objects.all(),
        }
    return render(request, 'gameadmin/add_entrance_exit.html', context)


def room_monster(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'monsters': Monsters.objects.all(),
        }
    return render(request, 'gameadmin/add_monster.html', context)


def room_killer(request):
    context = {
        'monster': Monsters.objects.get(id=request.POST['monster_id']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/room_killedby.html', context)

def room_trap(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'traps': Traps.objects.all(),
        }
    return render(request, 'gameadmin/room_traps.html', context)

def room_treasure(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'treasures': Treasures.objects.all(),
        }
    return render(request, 'gameadmin/room_treasure.html', context)

def room_visitor(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/currently_in.html', context)

def room_explorer(request):
    context = {
        'room': Rooms.objects.get(id=request.POST['room_id']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/explored_by.html', context)

def character_item(request):
    context = {
        'item': Items.objects.get(id=request.POST['item_id']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/character_item.html', context)

# ASSIGN
def assign_monster(request):
    print request.POST
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        monsterin = Monsters.objects.get(id=request.POST['monster'])
        room.monster.add(monsterin)

    return redirect(reverse ('Admin:admin_monsters'))

def assign_killer(request):
    if request.method == "POST":
        monster = Monsters.objects.get(id=request.POST['monster'])
        character = Characters.objects.get(id=request.POST['character'])
        monster.killed_by.add(character)
    return redirect(reverse ('Admin:admin_monsters'))

def assign_trap(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        trap = Traps.objects.get(id=request.POST['trap'])
        room.trap.add(trap)
    return redirect(reverse ('Admin:admin_rooms'))

def assign_explorer(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        character = Characters.objects.get(id=request.POST['character'])
        room.explored_by.add(character)
    return redirect(reverse ('Admin:admin_rooms'))


def assign_visitor(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        character = Characters.objects.get(id=request.POST['character'])
        room.currently_in.add(character)
    return redirect(reverse ('Admin:admin_rooms'))

def assign_treasure(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        treasure = Treasures.objects.get(id=request.POST['treasure'])
        room.treasure.add(treasure)
    return redirect(reverse ('Admin:admin_rooms'))

def assign_item(request):
    if request.method == "POST":
        character = Characters.objects.get(id=request.POST['character'])
        item = Items.objects.get(id=request.POST['item'])
        item.owned_by.add(character)
    context = {
        'item': Items.objects.get(id=request.POST['item']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/character_item.html', context)

# DELETE

def delete_monster(request):
    if request.method == "POST":
        Monsters.objects.filter(id=request.POST['monster']).delete()
    return redirect('/admin/admin_monsters')

def delete_item(request):
    if request.method == "POST":
        Items.objects.filter(id=request.POST['item']).delete()
    return redirect('/admin/admin_items')


def delete_treasure(request):
    if request.method == "POST":
        Treasures.objects.filter(id=request.POST['treasure']).delete()
    return redirect('/admin/admin_treasure')

def delete_user(request):
    if request.method == "POST":
        Users.objects.filter(id=request.POST['user']).delete()
    return redirect('/admin/admin_users')

def delete_character(request):
    if request.method == "POST":
        Characters.objects.filter(id=request.POST['character']).delete()
    return redirect('/admin/admin_characters')

def delete_trap(request):
    if request.method == "POST":
        Traps.objects.filter(id=request.POST['trap']).delete()
    return redirect('/admin/admin_traps')

def delete_room(request):
    if request.method == "POST":
        Rooms.objects.filter(id=request.POST['room']).delete()
    return redirect('/admin/admin_rooms')

# ADD
def add_exit(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['source'])
        exit = Rooms.objects.get(id=request.POST['destination'])
        direction = (request.POST['direction'])
        if request.POST['direction2']:
            direction2 = (request.POST['direction2'])
        else:
            direction2 = "None"
        Exits.objects.add_exit(room, exit, direction, direction2)

    return redirect('/admin')

def add_monster(request):
    if request.method == "POST":
        Monsters.objects.add_monster(request.POST)
    return redirect('/admin/admin_monsters')

def add_treasure(request):
    if request.method == "POST":
        Treasures.objects.add_treasure(request.POST)
    return redirect('/admin/admin_treasure')

def add_trap(request):
    if request.method == "POST":
        Traps.objects.add_trap(request.POST)
    return redirect('/admin/admin_traps')

def add_room(request):
    if request.method == "POST":
        Rooms.objects.add_room(request.POST)
    return redirect('/admin/admin_rooms')

def add_item(request):
    if request.method == "POST":
        Items.objects.add_item(request.POST)
    return redirect('/admin/admin_items')


# REMOVE

def remove_killer(request):
    if request.method == "POST":
        monster = Monsters.objects.get(id=request.POST['monster'])
        character = Characters.objects.get(id=request.POST['character'])
        monster.killed_by.remove(character)
    return redirect('/admin')

def remove_treasure(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        treasure = Treasures.objects.get(id=request.POST['treasure'])
        room.treasure.remove(treasure)
    return redirect('/admin')

def remove_monster(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        monsterin = Monsters.objects.get(id=request.POST['monster'])
        room.monster.remove(monsterin)
    return redirect('/admin')

def remove_visitor(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        character = Characters.objects.get(id=request.POST['character'])
        room.currently_in.remove(character)
    return redirect(reverse ('Admin:admin_rooms'))

def remove_explorer(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        character = Characters.objects.get(id=request.POST['character'])
        room.explored_by.remove(character)
    return redirect(reverse ('Admin:admin_rooms'))

def remove_trap(request):
    if request.method == "POST":
        room = Rooms.objects.get(id=request.POST['room'])
        trap = Traps.objects.get(id=request.POST['trap'])
        room.trap.remove(trap)
    return redirect(reverse ('Admin:room_trap'))

def remove_character(request):
    if request.method == "POST":
        character = Characters.objects.get(id=request.POST['character'])
        item = Items.objects.get(id=request.POST['item'])
        character.owner.remove(item)
    context = {
        'item': Items.objects.get(id=request.POST['item']),
        'characters': Characters.objects.all(),
        }
    return render(request, 'gameadmin/character_item.html', context)
# ADMIN EDIT PAGES


def admin_characters(request):
    context = {
        'users': Users.objects.all().order_by('username'),
        'characters': Characters.objects.all().order_by('name'),
        'items': Items.objects.all().order_by('name'),
        }
    return render(request, 'gameadmin/admin_character.html', context)

def admin_items(request):
    context = {
        'items': Items.objects.all().order_by('name'),
        'characters':Characters.objects.all().order_by('name')
        }

apps/gameadmin/templates/gameadmin/character_item.html
{% extends "gameadmin/base.html" %} {% include '/gameadmin/base.html' %}
{% block title %}Create{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'gameadmin/css/add.css' %}" /> {% endblock %}
{%block header %}Assign Owners to Items{% endblock %}
{% block content %}
<div id="wrapper">
	<h1>{{item.name}}</h1>
	<table>
		<tr>
			<th>Owner: </th>
			<th>Remove Owner </th>
		</tr>
		{% for character in characters %}
		{% for character_it in item.owned_by.all %}
		{% if character_it.id == character.id %}
		<tr>
			<td>{{character.name}}</td>
			<td><form action="remove_character" method="post">
				{% csrf_token %}
				<button type="submit">Remove Trap</button>
				<input type="hidden" name="character" value="{{character.id}}">
				<input type="hidden" name="item" value="{{item.id}}">
				<!-- <input type="hidden" name="item.id" value="{{item.id}}"> -->
				</form></td>
		</tr>
		{% endif %}
		{% endfor %}
		{% endfor %}
	</table>
	<table>
		<tr>
			<th>Available Owner: </th>
			<th>Assign Owner: </th>
		</tr>
		{% for character in characters %}
		{% if item.character.all %}
		{% for character_it in item.character.all %}
		{% if character_it.id != character.id %}
		<tr>
			<td>{{character.name}}</td>
			<td>
				<form action="assign_item" method="post">
				{% csrf_token %}
				<button type="submit">Assign character</button>
				<input type="hidden" name="character" value="{{character.id}}">
				<input type="hidden" name="item" value="{{item.id}}">
				</form>
			</td>
		</tr>
		{%endif%}
		{% endfor %}
		{% else %}
		{% if character_it.id != character.id %}
		<tr>
			<td>{{character.name}}</td>
			<td>
				<form action="assign_item" method="post">
				{% csrf_token %}
				<button type="submit">Assign character</button>
				<input type="hidden" name="character" value="{{character.id}}">
				<input type="hidden" name="item" value="{{item.id}}">
				</form>
			</td>
		</tr>
		{%endif%}
		{%endif%}
		{% endfor %}
	</table>
	<a href="{% url 'Admin:admin_items' %}">Go Back</a>
</div>
{% endblock %}

apps/gameadmin/templates/gameadmin/edit_character.html
{% extends "gameadmin/base.html" %} {% include '/gameadmin/base.html' %}
{% block title %}Admin - Edit Character{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'gameadmin/css/edit.css' %}" /> {% endblock %}
{% block scripts %}<script src="{% static 'gameadmin/js/sorttable.js' %}"></script>{% endblock %}
{%block header %}Admin - Edit Character {% endblock %}
{% block content %}
<div id="body">	
	<div id="header">
		<h1>{{characters.name}}</h1>
		<a href="/mainmenu/admin_menu">Admin Menu</a>
	</div>
	<div id="current">	
		<h2>Current Information:</h2>
		<table class="edit_characters">
			<tr>
                <th>ID:</th>
                <th>Name: </th>
                <th>Class: </th>
                <th>Strength: </th>
                <th>Dexterity: </th>
                <th>Intelligence: </th>
                <th>Health: </th>
                <th>Current Health:</th>
                <th>Gold: </th>
                <th>Killed By</th>
                <th>Level: </th>
                <th>Owned By: </th>
            </tr>
            <tr>
            	<td>{{characters.id}}</td>
        		<td>{{characters.name}}</td>
                <td>{{characters.cclass}}</td>
                <td>{{characters.strength}}</td>
                <td>{{characters.dexterity}}</td>
                <td>{{characters.intelligence}}</td>
                <td>{{characters.health}}</td>
                <td>{{characters.current_health}}</td>
                <td>{{characters.gold}}</td>
                <td>{{characters.killed_by}}</td>
                <td>{{characters.level}}</td>
                <th>{{characters.owned_by.username}}</th>
            </tr>
        </table>
    </div>
    <div id="edits">
    	<h2>Make Changes Below</h2>
    	<table class="change_characters">
    		<tr>
	    		<th>Name: </th>
	            <th>Class: </th>
	            <th>Strength: </th>
	            <th>Dexterity: </th>
	            <th>Intelligence: </th>
	            <th>Health: </th>
	            <th>Current Health:</th>
	            <th>Gold: </th>
	            <th>Killed By: </th>
	            <th>Level: </th>
	            <th>Submit: </th>
	        </tr>
	        <tr>
	        	<form action="{% url 'Admin:update_character' %}" method="post">
				<td><input class="user" type="text" name="name" value="{{characters.name}}"></td>
				<td><select id="selectchar" name="cclass">
					<option value="FI">FI</option>
					<option value="RO">RO</option>
					<option value="WI">WI</option>
					</select>
					</td>
				<td><input class="char" type="text" name="strength" value="{{characters.strength}}"></td>
				<td><input class="char" type="text" name="dext" value="{{characters.dexterity}}"></td>
				<td><input class="char" type="text" name="intel" value="{{characters.intelligence}}"></td>
				<td><input class="char" type="text" name="health" value="{{characters.health}}"></td>
				<td><input class="char" type="text" name="current_health" value="{{characters.current_health}}"></td>
				<td><input class="char" type="number" name="gold" value="{{characters.gold}}"></td>
				<td><input class="char" type="text" name="killed_by" value="{{characters.killed_by}}"></td>
				<td><input class="char" type="number" name="level" value="{{characters.level}}"></td>
				<td>{% csrf_token %}<input type="submit" name="submit" value="Save Changes">
				<input type="hidden" name="id" value="{{characters.id}}"></form></td>
				
			</tr>
		</table>
	</div>
	<div>
		<a href="{% url 'Admin:admin_characters' %}">Go Back</a>
		{% if messages %}
					<ul class="messages">
						{% for message in messages %}
							<li {% if message.tags %} class=" {{ message.tags }}" {% endif%}>
								{{ message }}
							</li>
						{% endfor %}
					</ul>
				{% endif %}

	</div>

{% endblock %}

apps/gameadmin/templates/gameadmin/edit_items.html
{% extends "gameadmin/base.html" %} {% include '/gameadmin/base.html' %}
{% block title %}Admin - Edit Item{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'gameadmin/css/edit.css' %}" /> {% endblock %}
{% block scripts %}<script src="{% static 'gameadmin/js/sorttable.js' %}"></script>{% endblock %}
{%block header %}Admin - Edit Item {% endblock %}
{% block content %}
<div id="body">	
	<div id="header">
		<h1>{{items.name}}</h1>
		<a href="/mainmenu/admin_menu">Admin Menu</a>
	</div>
	<div id="current">	
		<h2>Current Information:</h2>
		<table class="edit_characters">
			<tr>
                <th>ID:</th>
                <th>Name: </th>
                <th>Strength Bonus: </th>
                <th>Dexterity Bonus: </th>
                <th>Intelligence Bonus: </th>
                <th>Health Bonus: </th>
				<th>Consumable?:</th>
            </tr>
            <tr>
            	<td>{{items.id}}</td>
        		<td>{{items.name}}</td>
                <td>{{items.strbonus}}</td>
                <td>{{items.dexbonus}}</td>
                <td>{{items.intbonus}}</td>
                <td>{{items.hthbonus}}</td>
                <td>{{items.consumable}}</td>
            </tr>
        </table>
    </div>
    <div id="edits">
    	<h2>Make Changes Below</h2>
    	<table class="change_characters">
    		<tr>
	    		<th>ID:</th>
                <th>Name: </th>
                <th>Strength Bonus: </th>
                <th>Dexterity Bonus: </th>
                <th>Intelligence Bonus: </th>
                <th>Health Bonus: </th>
				<th>Consumable?:</th>
				<th>Submit:</th>
	        </tr>
	        <tr>
	        	<form action="{% url 'Admin:update_item' %}" method="post">
	        	<td>{{items.id}}</td>
				<td><input class="user" type="text" name="item" value="{{items.name}}"></td>
				<td><input type="number" name="strbonus" value="{{items.strbonus}}"></td>
				<td><input type="number" name="dexbonus" value="{{items.dexbonus}}"></td>
				<td><input type="number" name="intbonus" value="{{items.intbonus}}"></td>
				<td><input type="number" name="hthbonus" value="{{items.hthbonus}}"></td>
				<td><select name="consumable">
                    <option value="False">False</option>
                    <option value="True">True</option>
                    </select></td>
				<td>{% csrf_token %}<input type="submit" name="submit" value="Save Changes">
				<input type="hidden" name="id" value="{{items.id}}"></td>
				</form>
			</tr>
		</table>
    </div>    
        <div>
        <a href="{% url 'Admin:admin_items' %}">Go Back</a>
        {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class=" {{ message.tags }}" {% endif%}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
        </div>
</div>
{% endblock %}

apps/gameadmin/templates/gameadmin/edit_room.html
{% extends "gameadmin/base.html" %} {% include '/gameadmin/base.html' %}
{% block title %}Admin - Edit Rooms{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'gameadmin/css/edit.css' %}" /> {% endblock %}
{% block scripts %}<script src="{% static 'gameadmin/js/sorttable.js' %}"></script>{% endblock %}
{%block header %}Edit Rooms{% endblock %}
{% block content %}
<h2>{{rooms.name}}</h2>
<a id="room" href="/mainmenu/admin_menu">Admin Menu</a>
    <div id="first"> 
    	<h3>Current Information</h3>   
        <table class="current">
            <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Peek_Description</th>
              	<th>Terrain Type</th>
            </tr>
            <tr>
               <td>{{rooms.name}}</td>
               <td>{{rooms.description}}</td>
               <td>{{rooms.peek_description}}</td>
               <td>{{rooms.terrain_type}}</td>
            </tr>
        </table>
    </div>
    <div id="second">
		<h3>Make Changes Below:</h3>
    	<table class="change">
    		<tr>
				<th>Name</th>
	            <th>Description</th>
	            <th>Peek_Description</th>
	          	<th>Terrain Type</th>
	          	<th>Submit</th>
            </tr>
            <tr>
            	<form action="{% url 'Admin:update_room' %}" method="post">
            	<td><input type="text" class="user" name="name" value="{{rooms.name}}"></td>
            	<td><textarea name="description" placeholder="{{rooms.description}}"></textarea></td>
            	<td><textarea name="peek_description" placeholder="{{rooms.peek_description}}"></textarea></td>
            	<td><input type="text" name="terrain_type" class="user" value="{{rooms.terrain_type}}"></td>
            	<td>{% csrf_token %}
            	<input type="submit" name="submit" value="Save Changes"><input type="hidden" name="id" value="{{rooms.id}}"></td>
				</form>
			</tr>
		</table>
	</div>
    <div>
        <a href="{% url 'Admin:admin_rooms' %}">Go Back</a>

    </div>






{% endblock %}

apps/gameadmin/templates/gameadmin/edit_traps.html
{% extends "gameadmin/base.html" %} {% include '/gameadmin/base.html' %}
{% block title %}Admin - Edit Traps{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'gameadmin/css/edit.css' %}" /> {% endblock %}
{%block header %}Edit Traps{% endblock %}
{% block content %}
<div id="edittrap">	
	<div id="header">
		<h1>{{traps.name}}</h1>
		<a href="/mainmenu/admin_menu">Admin Menu</a>
	</div>
	<div id="current">	
		<h2>Current Information:</h2>
		<table class="top">
			<tr>	
				<th>Name:</th>
				<th>Class</th>
				<th>Strength</th>
			</tr>
			
			<tr>
				<td>{{traps.name}}</td>
				<td>{{traps.tclass}}</td>
				<td>{{traps.strength}}</td>
			</tr>
			
		</table>
	</div>
	<div id="edits">
		<h2>Make Changes Below:</h2>
		<table class="abc">
			<tr>
				<th>Name:</th>
				<th>Class</th>
				<th>Strength</th>
				<th>Submit:</th>
			</tr>
			<tr>
				<form action="{% url 'Admin:update_trap' %}" method="post">
				<th><input class="user" type="text" name="name" value="{{traps.name}}"></th>
				<th><select id="selectchar" name="class" value="{{traps.tclass}}">
					<option>PZ</option>
					<option>PS</option>
					<option>RF</option>
					<option>CL</option>
				</select></th>
				<th><input class="user" type="number" name="strength" value="{{traps.strength}}"></th>
				<th>{% csrf_token %}<input class="users" type="submit" name="submit" value="Save Changes">
				<input type="hidden" name="id" value="{{traps.id}}"></th>
				</form>
			</tr>
		</table>
	</div>
	<div>
		<a href="{% url 'Admin:admin_traps' %}">Go Back</a>
		{% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li {% if message.tags %} class=" {{ message.tags }}" {% endif%}>
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
	</div>
</div>
{% endblock %}