apps/login/urls.py
from django.conf.urls import url
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^main$', views.main, name='login_main'),
    url(r'^log_in$', views.login, name='log-in'),
    url(r'^checklogin$', views.login),
    url(r'^register$', views.register),
    url(r'logout$', views.logout, name='logout'),
    url(r'^$', views.index, name='index'),
]

apps/mainmenu/urls.py
from django.conf.urls import url
from django.conf.urls import url
from . import views
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create$', views.create, name='create'),
	url(r'^delete$', views.delete, name='delete'),
	url(r'^hall$', views.hall, name='hall'),
	url(r'^updatechar$', views.update),
	url(r'^roll$', views.roll, name='roll'),
	url(r'^show$', views.showcreate, name='show'),
	url(r'^create$', views.create),
	url(r'^admin_menu$', views.admin_menu, name='admin_menu'),
	url(r'^select_character$', views.select_character, name='select_character'),

]

thegame/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^game/', include('apps.game.urls', namespace='Game')),
    url(r'^mainmenu/', include('apps.mainmenu.urls', namespace='Mainmenu')),
    url(r'^login/', include('apps.login.urls', namespace='Login')),
    url(r'^admin/', include('apps.gameadmin.urls', namespace='Admin')),
    url(r'^', include('apps.login.urls', namespace='Login')),
]

apps/mainmenu/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import Users

apps/mainmenu/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from random import randint
import random
from django.core.urlresolvers import reverse
from ..game.models import Characters, Rooms
from ..login.models import Users


def index(request):
	request.session['starting_room']="1"
	return render(request, 'mainmenu/index.html')


def showcreate(request):
	return render(request, 'mainmenu/newchar.html')


def create(request):
	if request.method=='POST':
		user = Users.objects.get(id=request.session['user_id'])
		response_from_models=Characters.objects.add_char(request.POST, user)
		if response_from_models['status']:
			hero=response_from_models["character"]
			room=Rooms.objects.get(id=request.session['starting_room'])
			room.explored_by.add(hero)
			room.currently_in.add(hero)
			request.session['character_id']=hero.id
			return redirect('/game')
		else:
			for error in response_from_models['errors']:
				messages.info(request, error)
	return redirect(reverse('Mainmenu:show'))


def delete(request):
    return render(request, 'login/base.html')


def admin_menu(request):
	return render(request, 'gameadmin/adminmenu.html')


def hall(request):
	context = {
	'characters':Characters.objects.filter(level__gt=0).order_by('-gold'),
	}
	return render(request, 'mainmenu/hall.html', context)

def update(request):
	context = {
	'characters':Characters.objects.filter(level>0).order_by('gold'),
	}
	return render(request, 'mainmenu/hall.html', context)


def roll(request):
	strength= (random.randrange(1,5) + random.randrange(1,5) + random.randrange(1,5))
	dexterity= (random.randrange(1,5) + random.randrange(1,5) + random.randrange(1,5))
	intelligence= (random.randrange(1,5) + random.randrange(1,5) + random.randrange(1,5))
	health= (random.randrange(1,5) + random.randrange(1,5) + random.randrange(1,5))
	context = {
			'str': strength,
			'dex': dexterity,
			'int': intelligence,
			'hea': health
			}
	return render(request, 'mainmenu/newchar.html', context)


def select_character(request):
    context = {
        'characters': Characters.objects.filter(owned_by__id=request.session['user_id']).order_by('name'),
        }
    return render(request, 'mainmenu/select_character.html', context)

apps/mainmenu/templates/mainmenu/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"> {% load static %}
    {% block loads %} {%endblock%}
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/base.css' %}">
    {% block css %}{% endblock %}
    <title> {% block title %}Belt Test Main Page{% endblock %}</title>
</head>

<body>
    <div id="container">
        <header id='headerblock'>
            <div id="logoblock">
                <img src="{% static 'login/img/Lorem_Ipsum.svg' %}" alt="Logo Placeholder">

            </div>
            <div id="titleblock">
                <h1>Lorem ipsum dolor sit </h1>
            </div>
            <div id="loginblock">
                {% if request.session.user_id %}
                <p></p>
                Hello {{request.session.username}}
                 {# TODO logged in logic#}
                 <p></p>
                 <p></p>
                 <form action="/Login/logout" method="post">
                     {% csrf_token %}
                     <button type="submit" name="login">Log out</button>

                 </form>
                {% else %}
                <p></p>
                <p>Please Log in</p>
                <p></p>
                <p></p>
                {# TODO not logged in logic#}
                <form action="/login">
                    <button type="submit" name="login">Log in</button>

                </form>
                {% endif %}
            </div>
        </header>
        <div id="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</body>

</html>

apps/mainmenu/templates/mainmenu/hall.html
{% extends "login/base.html" %} {% include '/login/base.html' %}
{% block title %}Create{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'mainmenu/css/hall.css' %}" /> {% endblock %}

{% block content %}
<div id="wrapper">
	<div id="header">
		<h1>Hall of Fame!</h1>
	</div>
	<div id="links">
		<a href="{% url 'Mainmenu:index' %}">Home</a>
		<a href="{% url 'Login:logout' %}">Logout</a>
	</div>
	<div id="main">
		<table>
			<tr>
				<th>Hero</th>
				<th>User</th>
				<th>Gold</th>
			</tr>
			{% for character in characters %}
			<tr>
				<td>{{character.name}}</td>
				<td>{{character.owned_by.username}}</td>
				<td>{{character.gold}}</td>
			</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

apps/mainmenu/templates/mainmenu/index.html
{% extends "login/base.html" %} {% include '/login/base.html' %}
{% block title %}Main Menu{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'mainmenu/css/index.css' %}" /> {% endblock %}

{% block content %}
<div id="wrapper">
	<div id="header">
		<h1>Main Menu</h1>
	</div>
	<div id="menu">
		<ul>
			<li><a href="{% url 'Mainmenu:admin_menu' %}">Admin</a></li>
			<li><a href="{% url 'Mainmenu:select_character' %}">Continue</a></li>
			<li><a href="{% url 'Mainmenu:roll' %}">New Character</a></li>
			<li><a href="{% url 'Mainmenu:delete' %}">Delete Character</a></li>
			<li><a href="{% url 'Mainmenu:hall' %}">Hall of Fame</a></li>
			<li><a href="{% url 'Login:logout' %}">Quit Game</a></li>
		</ul>
	</div>
</div>
{% endblock %}

apps/mainmenu/templates/mainmenu/newchar.html
{% extends "login/base.html" %} {% include '/login/base.html' %}
{% block title %}Create{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'mainmenu/css/newchar.css' %}" /> {% endblock %}

{% block content %}

<div id="wrapper">
	<div id="header">
		<h1>Create a New Character</h1>
	</div>
	<div id="main">
	<form id="createchar" action="{% url 'Mainmenu:create' %}" method="post">
		<table>
			<tr>
				<td align="left">Name: </td>
				<td align="right"><input type="text" name="char_name" class="boxa"></td>
			</tr>
			<tr>
				<td align="left">Class: </td>
				<td align="right"><select name="add_class">
					<option value="FI">Fighter (+5 strength)</option>
					<option value="RO">Rogue (+5 dexterity)</option>
					<option value="WI">Wizard (+5 intelligence)</option>
				</select></td>
			</tr>
			<tr>
				<td align="left">Stats: </td>
			</tr>
			<tr>
				<td align="left"></td>
				<td align="right">Strength: <input type="hidden" name="strength" value="{{str}}">{{str}} </td>
			</tr>
			<tr>
				<td align="left"></td>
				<td align="right">Dexterity:<input type="hidden" name="dext" value="{{dex}}"> {{dex}}</td>
			</tr>
			<tr>
				<td align="left"></td>
				<td align="right">Intelligence:<input type="hidden" name="intel" value="{{int}}"> {{int}}</td>
			</tr>
			<tr>
				<td align="left"></td>
				<td align="right">Health:<input type="hidden" name="health" value="{{hea}}"> {{hea}}</td>
			</tr>
		</table>
		<div>
		{% csrf_token %}
		<input type="submit" name="savechar" id="save" value="Save Character">
		</div>
	</form>

		<div id="dice">
			<a href="/mainmenu/roll">Roll Dice</a>
			<!-- #TODO (make 3 rolls) -->
			<!-- <br><br><p>3 Rolls Left</p> -->
		</div>
		<div id="bottom">
			<a href="{% url 'Mainmenu:index' %}">Home</a>
			<a href="{% url 'Login:logout' %}">Quit/Logout</a>
		</div>
	</div>
	{% if messages %}
        <ul class="messages">
        {% for message in messages %}
           <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
</div>
{% endblock %}

apps/mainmenu/templates/mainmenu/select_character.html
{% extends "login/base.html" %} {% include '/login/base.html' %}
{% block title %}Create{% endblock %}
{% block loads %}{% load static %} {% endblock %}
{% block css %} <link rel="stylesheet" type="text/css" href="{% static 'mainmenu/css/hall.css' %}" /> {% endblock %}

{% block content %}
<div id="links">
<a href="{% url 'Mainmenu:index' %}">Home</a>
<a href="{% url 'Login:logout' %}">Logout</a>
</div>
{% for character in characters %}
<table>
<tr>
	<td class="left" align="left">
		{{character.name}}
	</td>
	<td align="right">
		<form action="/game/start_game" method="post">
			{% csrf_token %}
			<button class="right"type="submit">Select and Start</button>
			<input type="hidden" name="character" value="{{character.id}}">
		</form>
	</td>
</tr>
{% endfor %}
</table>
{% endblock %}